package powerlevel10k

import (
	"bytes"
	"reflect"
	"strings"
	"testing"
)

const sampleConfig = `# Generated by Powerlevel10k configuration wizard.
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  # os_icon
  dir                     # current directory
  vcs                     # git status
  newline                 # prompt line break
  prompt_char             # prompt symbol
)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time time)
typeset -g POWERLEVEL9K_MODE=nerdfont-complete
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s' # duration format
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION='❯'
typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE="%n@%m"
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
`

func TestFindValue(t *testing.T) {
	p := newParser()
	tests := []struct {
		key  string
		want string
		ok   bool
	}{
		{"POWERLEVEL9K_MODE", "nerdfont-complete", true},
		{"POWERLEVEL9K_PROMPT_ADD_NEWLINE", "true", true},
		{"POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT", "d h m s", true},
		{"POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION", "❯", true},
		{"POWERLEVEL9K_CONTEXT_TEMPLATE", "%n@%m", true},
		{"POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS", "status, command_execution_time, time", true},
		{"POWERLEVEL9K_MISSING", "", false},
	}

	for _, tt := range tests {
		t.Run(tt.key, func(t *testing.T) {
			got, ok := p.FindValue([]byte(sampleConfig), tt.key)
			if ok != tt.ok || got != tt.want {
				t.Fatalf("FindValue(%q) = %q, %v; want %q, %v", tt.key, got, ok, tt.want, tt.ok)
			}
		})
	}
}

func TestFindValues(t *testing.T) {
	p := newParser()
	got, ok := p.FindValues([]byte(sampleConfig), "POWERLEVEL9K_LEFT_PROMPT_ELEMENTS")
	want := []string{"dir", "vcs", "newline", "prompt_char"}
	if !ok || !reflect.DeepEqual(got, want) {
		t.Fatalf("FindValues(left) = %v, %v; want %v, true", got, ok, want)
	}

	got, ok = p.FindValues([]byte(sampleConfig), "POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS")
	want = []string{"status", "command_execution_time", "time"}
	if !ok || !reflect.DeepEqual(got, want) {
		t.Fatalf("FindValues(right) = %v, %v; want %v, true", got, ok, want)
	}
}

func TestSetValuePreservesInlineComment(t *testing.T) {
	p := newParser()
	got, err := p.SetValue([]byte(sampleConfig), "POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT", "'h m s'")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(got, []byte("typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='h m s' # duration format")) {
		t.Fatalf("SetValue did not preserve inline comment:\n%s", got)
	}
	v, ok := p.FindValue(got, "POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT")
	if !ok || v != "h m s" {
		t.Fatalf("FindValue after SetValue = %q, %v; want h m s, true", v, ok)
	}
}

func TestSetValuesReplacesArrayBlock(t *testing.T) {
	p := newParser()
	got, err := p.SetValues([]byte(sampleConfig), "POWERLEVEL9K_LEFT_PROMPT_ELEMENTS", []string{"dir", "vcs", "prompt_char"})
	if err != nil {
		t.Fatal(err)
	}
	wantBlock := `typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  dir
  vcs
  prompt_char
)`
	if !strings.Contains(string(got), wantBlock) {
		t.Fatalf("SetValues missing block:\n%s", got)
	}
	vals, ok := p.FindValues(got, "POWERLEVEL9K_LEFT_PROMPT_ELEMENTS")
	want := []string{"dir", "vcs", "prompt_char"}
	if !ok || !reflect.DeepEqual(vals, want) {
		t.Fatalf("FindValues after SetValues = %v, %v; want %v, true", vals, ok, want)
	}
	if _, ok := p.FindValue(got, "POWERLEVEL9K_MODE"); !ok {
		t.Fatal("SetValues lost following assignments")
	}
}

func TestSetValuesAddsArray(t *testing.T) {
	p := newParser()
	got, err := p.SetValues([]byte("typeset -g POWERLEVEL9K_MODE=ascii\n"), "POWERLEVEL9K_VCS_BACKENDS", []string{"git", "hg"})
	if err != nil {
		t.Fatal(err)
	}
	want := "typeset -g POWERLEVEL9K_MODE=ascii\ntypeset -g POWERLEVEL9K_VCS_BACKENDS=(\n  git\n  hg\n)\n"
	if string(got) != want {
		t.Fatalf("SetValues add mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestDeleteKeyRemovesArrayBlock(t *testing.T) {
	p := newParser()
	got, err := p.DeleteKey([]byte(sampleConfig), "POWERLEVEL9K_LEFT_PROMPT_ELEMENTS")
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Contains(got, []byte("current directory")) || bytes.Contains(got, []byte("prompt_char")) {
		t.Fatalf("DeleteKey left array left block content:\n%s", got)
	}
	if _, ok := p.FindValue(got, "POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS"); !ok {
		t.Fatal("DeleteKey lost right prompt array")
	}
}

func TestFindAllMulti(t *testing.T) {
	p := newParser()
	singles, multi := p.FindAllMulti([]byte(sampleConfig))
	if singles["POWERLEVEL9K_MODE"] != "nerdfont-complete" {
		t.Fatalf("FindAllMulti mode = %q", singles["POWERLEVEL9K_MODE"])
	}
	want := []string{"dir", "vcs", "newline", "prompt_char"}
	if !reflect.DeepEqual(multi["POWERLEVEL9K_LEFT_PROMPT_ELEMENTS"], want) {
		t.Fatalf("FindAllMulti left = %v, want %v", multi["POWERLEVEL9K_LEFT_PROMPT_ELEMENTS"], want)
	}
}

func TestListKeys(t *testing.T) {
	p := newParser()
	keys := p.ListKeys([]byte(sampleConfig))
	want := map[string]bool{
		"POWERLEVEL9K_LEFT_PROMPT_ELEMENTS":                   true,
		"POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS":                  true,
		"POWERLEVEL9K_MODE":                                   true,
		"POWERLEVEL9K_PROMPT_ADD_NEWLINE":                     true,
		"POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT":          true,
		"POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION": true,
		"POWERLEVEL9K_CONTEXT_TEMPLATE":                       true,
		"POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD":           true,
	}
	for _, key := range keys {
		if !want[key] {
			t.Fatalf("unexpected key %q in %v", key, keys)
		}
		delete(want, key)
	}
	if len(want) != 0 {
		t.Fatalf("missing keys: %v", want)
	}
}

func FuzzParser(f *testing.F) {
	f.Add([]byte(sampleConfig), "POWERLEVEL9K_MODE")
	f.Add([]byte("typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)\n"), "POWERLEVEL9K_LEFT_PROMPT_ELEMENTS")
	f.Add([]byte("POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true\n"), "POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD")
	f.Add([]byte(""), "POWERLEVEL9K_MISSING")

	p := newParser()
	f.Fuzz(func(t *testing.T, data []byte, key string) {
		p.FindValue(data, key)
		p.FindLine(data, key)
		p.ListKeys(data)
		if out, err := p.SetValue(data, key, "'fuzzval'"); err == nil {
			p.FindValue(out, key)
			p.ListKeys(out)
		}
		if out, err := p.SetValues(data, key, []string{"dir", "vcs"}); err == nil {
			p.FindValues(out, key)
			p.ListKeys(out)
		}
		p.DeleteKey(data, key)
	})
}
